apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-edge-backend
  namespace: iot-edge
  labels:
    app: iot-edge-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: iot-edge-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: iot-edge-backend
    spec:
      containers:
      - name: iot-edge-backend
        image: ${ACR_NAME}.azurecr.io/iot-edge-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "5000"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: iot-edge-secrets
              key: db-host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: iot-edge-secrets
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: iot-edge-secrets
              key: db-password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: iot-edge-secrets
              key: db-name
        - name: REDIS_HOST
          value: "iot-edge-redis"
        - name: REDIS_PORT
          value: "6379"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: iot-edge-secrets
              key: jwt-secret
        - name: JWT_EXPIRES_IN
          value: "24h"
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
      imagePullSecrets:
      - name: acr-auth